#### TÄND_FÖNSTERLAMPOR PÅ KVÄLLEN
- alias: Tänd fönsterlampor innan solen går ner
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:35:00"
  action:
    - service: scene.turn_on
      entity_id: scene.fonsterlampor_pa
    - service: notify.pushbullet
      data:
        message: 'Tänder fönsterlampor'
        title: 'Home Assistant'

#### TÄND_FÖNSTERLAMPOR PÅ KVÄLLEN MED LJUSSENSOR
- alias: Tänd fönsterlampor när det mörknar
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: sensor.is_dark
      from: 'False'
      to: 'True'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.sn1_led
        brightness: 200
        rgb_color: [255, 0, 0]

#### SLÄCK FÖNSTERLAMPOR
- alias: Släck fönsterlampor
  trigger:
    - platform: time
      at: '01:00:00'
  action: 
    service: scene.turn_on
    entity_id: scene.fonsterlampor_av

#### SLÄCK FÖNSTERLAMPOR NÄR TVn STÄNGS AV
- alias: Släck fönsterlampor när TVn stängs av
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: media_player.tv_vardagsrum
      from: 'on'
      to: 'off'
  action:
    - delay: '00:01:00'
    - service: scene.turn_on
      entity_id: scene.fonsterlampor_av

#### DÖRRKLOCKA
- alias: Dörrklocka
  hide_entity: False
  trigger:
    - platform: state
      entity_id: light.aster_0074_01
  action:
    - service: notify.pushbullet
      data_template:
        target: "device/Galaxy S6 Edge"
        title: "Homeassistant"
        message: "Det ringer på dörren"

#### Taklampa sovrum
#- alias: Taklampa sovrum
#  trigger:
#    - platform: time
#      at: '05:45:00'
#  condition:
#    - condition: state
#      entity_id: binary_sensor.workday_sensor
#      state: 'on'
#  action:
#    service: light.turn_on
#    data:
#      entity_id: light.fibaro_system_fgd212_dimmer_2_level
#      brightness: 25

#### Starta kaffebryggaren på morgonen
#- alias: Starta kaffebryggaren på morgonen
#  initial_state: 'off'
#  trigger:
#    - platform: time
#      at: '05:40:00'
#  action: 
#    - service: switch.turn_on
#      entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
#    - service: automation.turn_off
#      entity_id: automation.starta_kaffebryggaren_pa_morgonen

#### Starta kaffebryggaren
- alias: "Starta kaffebryggaren"
  initial_state: 'off'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.coffee_time.state }}'
  action: 
    - service: switch.turn_on
      entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
    - service: automation.turn_off
      entity_id: automation.starta_kaffebryggaren

#### Stäng av kaffebryggaren efter 30 minuter
- alias: Stäng av kaffebryggaren efter 30 minuter
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
    to: 'on'
    for:
      minutes: 30
  action:
    service: switch.turn_off
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch

#### Meddela när kaffet är färdigt
- alias: Kaffet är färdigt
  trigger:
    platform: state
    entity_id: sensor.coffee_brewing
    from: 'True'
    to: 'False'
  action:
    service: notify.pushbullet
    data:
      message: "Kaffet är färdigt"

#### Taklampa sovrum
- alias: "Taklampa sovrum"
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.bedroom_time.state }}'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level
      brightness: '{{ states.input_slider.bedroom_brightness.state | int }}'
      transition: '{{ states.input_slider.bedroom_transition.state | int }}'

#### SONOFF
- alias: Sonoff01 on
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_5
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.skarvsladd_1
- alias: Sonoff01 off
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_5
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.skarvsladd_1

- alias: Sonoff02 on
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_6
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.skarvsladd_2
- alias: Sonoff02 off
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_6
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.skarvsladd_2

- alias: Sonoff03 on
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_4
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.win_kitchen1
- alias: Sonoff03 off
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_4
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.win_kitchen1

- alias: Sonoff04 on
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_4
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.win_kitchen2
- alias: Sonoff04 off
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_4
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.win_kitchen2

- alias: Sonoff05 on
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_3
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.win_bedroom
- alias: Sonoff05 off
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_3
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.win_bedroom

- alias: Sonoff06 on
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_1
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.win_livingroom_1
- alias: Sonoff06 off
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_1
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.win_livingroom_1

- alias: Sonoff07 on
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_2
    to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.win_livingroom_2
- alias: Sonoff07 off
  trigger:
    platform: state
    entity_id: light.newkaku_00d8893a_2
    to: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.win_livingroom_2

#### UPPDATERA FJÄRRKONTROLL
#### KNAPP 1 Vardagsrum 1
- alias: Knapp 1 ON
  trigger:
    platform: mqtt
    topic: stat/sonoff06/POWER
    payload: 'ON'
  action:
    service: light.turn_on
    entity_id: light.newkaku_00d8893a_1

- alias: Knapp 1 OFF
  trigger:
    platform: mqtt
    topic: stat/sonoff06/POWER
    payload: 'OFF'
  action:
    service: light.turn_off
    entity_id: light.newkaku_00d8893a_1

#### KNAPP 2 Vardagsrum 2
- alias: Knapp 2 ON
  trigger:
    platform: mqtt
    topic: stat/sonoff07/POWER
    payload: 'ON'
  action:
    service: light.turn_on
    entity_id: light.newkaku_00d8893a_2

- alias: Knapp 2 OFF
  trigger:
    platform: mqtt
    topic: stat/sonoff07/POWER
    payload: 'OFF'
  action:
    service: light.turn_off
    entity_id: light.newkaku_00d8893a_2

#### KNAPP 3 Sovrum
- alias: Knapp 3 ON
  trigger:
    platform: mqtt
    topic: stat/sonoff05/POWER
    payload: 'ON'
  action:
    service: light.turn_on
    entity_id: light.newkaku_00d8893a_3

- alias: Knapp 3 OFF
  trigger:
    platform: mqtt
    topic: stat/sonoff05/POWER
    payload: 'OFF'
  action:
    service: light.turn_off
    entity_id: light.newkaku_00d8893a_3

#### KNAPP 4 Kök
- alias: Knapp 4 ON
  trigger:
    - platform: mqtt
      topic: stat/sonoff03/POWER
      payload: 'ON'
    - platform: mqtt
      topic: stat/sonoff04/POWER
      payload: 'ON'
  action:
    service: light.turn_on
    entity_id: light.newkaku_00d8893a_4

- alias: Knapp 4 OFF
  trigger:
    - platform: mqtt
      topic: stat/sonoff03/POWER
      payload: 'OFF'
    - platform: mqtt
      topic: stat/sonoff04/POWER
      payload: 'OFF'
  action:
    service: light.turn_off
    entity_id: light.newkaku_00d8893a_4

#### RÖRELSE
- alias: Tänd lampa vid rörelse
  trigger:
    platform: state
    entity_id: sensor.sn2_pir
    to: '1'
  action:
    service: switch.turn_on
    entity_id: switch.skarvsladd_1

- alias: Släck lampa efter rörelse
  trigger:
    platform: state
    entity_id: sensor.sn2_pir
    to: '0'
    for:
      minutes: 1
  action:
    service: switch.turn_off
    entity_id: switch.skarvsladd_1