#### TÄND_FÖNSTERLAMPOR MED SOLHÖJD
- alias: Tänd fönsterlampor när solen står lågt
  trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
  action:
    - service: scene.turn_on
      entity_id: scene.fonsterlampor_pa
    - service: notify.pushbullet
      data:
        message: 'Tänder fönsterlampor'
        title: 'Home Assistant'

#### TÄND_FÖNSTERLAMPOR PÅ KVÄLLEN
#- alias: Tänd fönsterlampor innan solen går ner
#  trigger:
#    - platform: sun
#      event: sunset
#      offset: "-00:35:00"
#  action:
#    - service: scene.turn_on
#      entity_id: scene.fonsterlampor_pa
#    - service: notify.pushbullet
#      data:
#        message: 'Tänder fönsterlampor'
#        title: 'Home Assistant'

#### TÄND_FÖNSTERLAMPOR PÅ KVÄLLEN MED LJUSSENSOR
#- alias: Tänd fönsterlampor när det mörknar
#  initial_state: 'off'
#  trigger:
#    - platform: state
#      entity_id: sensor.is_dark
#      from: 'False'
#      to: 'True'
# action:
#    - service: light.turn_on
#      data_template:
#        entity_id: light.sn1_led
#        brightness: 200
#        rgb_color: [255, 0, 0]

#### SLÄCK FÖNSTERLAMPOR
- alias: Släck fönsterlampor
  trigger:
    - platform: time
      at: '01:00:00'
  action: 
    service: scene.turn_on
    entity_id: scene.fonsterlampor_av

#### SLÄCK FÖNSTERLAMPOR NÄR TVn STÄNGS AV
- alias: Släck fönsterlampor när TVn stängs av
  initial_state: 'off'
  trigger:
    - platform: state
      entity_id: media_player.tv_vardagsrum
      from: 'on'
      to: 'off'
  action:
    - delay: '00:01:00'
    - service: scene.turn_on
      entity_id: scene.fonsterlampor_av

#### DÖRRKLOCKA
- alias: Dörrklocka
  hide_entity: False
  trigger:
    - platform: state
      entity_id: light.aster_0074_01
  action:
    service: notify.pushbullet
    data:
      message: "Det ringer på dörren"
      title: 'Home Assistant'

#### Brandlarm
- alias: Brandlarm
  hide_entity: False
  trigger:
    - platform: state
      entity_id: light.fa20rf_e5885b_01
  action:
    service: notify.pushbullet
    data:
      message: "Brandlarm!!!"
      title: 'Home Assistant'

#### Taklampa sovrum
#- alias: Taklampa sovrum
#  trigger:
#    - platform: time
#      at: '05:45:00'
#  condition:
#    - condition: state
#      entity_id: binary_sensor.workday_sensor
#      state: 'on'
#  action:
#    service: light.turn_on
#    data:
#      entity_id: light.fibaro_system_fgd212_dimmer_2_level
#      brightness: 25

#### Starta kaffebryggaren på morgonen
#- alias: Starta kaffebryggaren på morgonen
#  initial_state: 'off'
#  trigger:
#    - platform: time
#      at: '05:40:00'
#  action: 
#    - service: switch.turn_on
#      entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
#    - service: automation.turn_off
#      entity_id: automation.starta_kaffebryggaren_pa_morgonen

#### Starta kaffebryggaren
- alias: "Starta kaffebryggaren"
  initial_state: 'off'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  condition:
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.coffee_time.state }}'
  action: 
    - service: switch.turn_on
      entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
    - service: automation.turn_off
      entity_id: automation.starta_kaffebryggaren

#### Stäng av kaffebryggaren efter 30 minuter
- alias: Stäng av kaffebryggaren efter 30 minuter
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
    to: 'on'
    for:
      minutes: 30
  action:
    service: switch.turn_off
    entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch

#### Meddela när kaffet är färdigt
- alias: Kaffet är färdigt
  trigger:
    platform: state
    entity_id: sensor.coffee_brewing
    from: 'True'
    to: 'False'
  action:
    service: notify.pushbullet
    data:
      message: "Kaffet är färdigt"
      title: 'Home Assistant'

#### Taklampa sovrum
- alias: "Sovrum taklampa automatik"
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ now().strftime("%H:%M") == states.sensor.bedroom_time.state }}'
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level
      brightness: '{{ states.input_number.bedroom_brightness.state | int }}'
      transition: '{{ states.input_number.bedroom_transition.state | int * 60 }}'

#### RÖRELSE
- alias: Tänd lampa vid rörelse
  trigger:
    platform: state
    entity_id: sensor.sn2_pir
    to: '1'
  action:
    service: scene.turn_on
    entity_id: scene.led_strip_brown
    #service: light.turn_on
    #entity_id: light.floalt_panel_ws_30x30
    

- alias: Släck lampa efter rörelse
  trigger:
    platform: state
    entity_id: sensor.sn2_pir
    to: '0'
    for:
      minutes: 5
  action:
    service: light.turn_off
    #entity_id: light.floalt_panel_ws_30x30
    entity_id: light.led_strip

#### LED-strip
- alias: LED-strip
  trigger:
#    - platform: state
#      entity_id: input_number.led_strip_r
#    - platform: state
#      entity_id: input_number.led_strip_g
#    - platform: state
#      entity_id: input_number.led_strip_b
    - platform: state
      entity_id: input_number.led_strip_bright
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.led_strip
        brightness: '{{ states.input_number.led_strip_bright.state | int }}'
#        rgb_color: '{{ states.sensor.slider_rgb_led_strip.state }}'

- alias: LED-strip-ljus
  trigger:
    - platform: state
      entity_id: sensor.rgb_led_strip_pv
  action:
    - service: input_number.select_value
      data_template:
        entity_id: input_number.led_strip_bright
        value: '{{ states.light.led_strip.attributes.brightness }}'

#### Stäng av uttag vid sängen kl 9 när jag inte är hemma
- alias: Stäng av uttag vid sängen
  trigger:
    - platform: time
      at: '09:00:00'
  condition:
    condition: template
    value_template: "{{ not is_state('device_tracker.ke', 'home') }}"
  action: 
    service: switch.turn_off
    entity_id: switch.sanglampa

#### Xiaomi knapp 1
- alias: Fönsterlampor av, Single click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00019ca56e
      click_type: single
  action:
    - service: scene.turn_on
      entity_id: scene.fonsterlampor_av

- alias: Fönsterlampor på, Double click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00019ca56e
      click_type: double
  action:
    - service: scene.turn_on
      entity_id: scene.fonsterlampor_pa

- alias: Godnatt, long click press
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00019ca56e
      click_type: long_click_press
  action:
    - service: scene.turn_on
      entity_id: scene.godnatt

#### Xiaomi knapp 2
- alias: Dörrklocka, Single click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00019c8c02
      click_type: single
  action:
#    - service: xiaomi_aqara.play_ringtone
#      data_template:
#        gw_mac: !secret xiaomi_mac
#        ringtone_id: 10
#        ringtone_vol: 70
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          where: 'media_player.kok'
          what: 'Nån ringer på dörren'

#### Xiaomi Balkongdörr öppnas
- alias: Balkongdörr öppnas
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001b8623f
      from: 'off'
      to: 'on'
  action:
    - service: notify.pushbullet
      data:
        message: 'Balkongdörr öppnad'
        title: 'Home Assistant'
#    - service: xiaomi_aqara.play_ringtone
#      data_template:
#        gw_mac: !secret xiaomi_mac
#        ringtone_id: 10
#        ringtone_vol: 15

#### Xiaomi Balkongdörr stängs
- alias: Balkongdörr stängs
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001b8623f
      from: 'on'
      to: 'off'
  action:
    - service: notify.pushbullet
      data:
        message: 'Balkongdörr stängd'
        title: 'Home Assistant'

#### Xiaomi Diskmaskin översvämmning
- alias: Diskmaskin översvämmning
  trigger:
    - platform: state
      entity_id: binary_sensor.water_leak_sensor_158d0001bc1fab
      from: 'off'
      to: 'on'
  action:
    - service: notify.pushbullet
      data:
        message: 'Diskmaskinen läcker'
        title: 'Home Assistant'

#### Belysning hall
- alias: Tänd hallampa vid rörelse
  trigger:
    platform: state
    entity_id: sensor.pir_hall
    to: '1'
  condition:
  - condition: time
    after: '00:00:00'
    before: '06:00:00'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.fibaro_system_fgd212_dimmer_2_level_5
      brightness: 8
    

- alias: Släck hallampa efter rörelse
  trigger:
    platform: state
    entity_id: sensor.pir_hall
    to: '0'
    for:
      minutes: 1
  condition:
  - condition: time
    after: '00:00:00'
    before: '06:00:00'
  action:
    service: light.turn_off
    entity_id: light.fibaro_system_fgd212_dimmer_2_level_5