#- platform: owntracks

- platform: mqtt_json
  devices:
    ke: 'zanzito/ke/location'

- platform: nmap_tracker
  hosts: 192.168.0.1/24
  exclude:
   - 192.168.0.128
   
- platform: bluetooth_tracker