- platform: rflink

- platform: moon

- platform: season

- platform: snmp
  host: 192.168.0.115
  name: CPU-temperature
  unit_of_measurement: '°C'
  community: monitor
  baseoid: 1.3.6.1.4.1.6574.1.2.0

- platform: snmp
  host: 192.168.0.115
  name: HD1-temperature
  unit_of_measurement: '°C'
  community: monitor
  baseoid: 1.3.6.1.4.1.6574.2.1.1.6.0

- platform: snmp
  host: 192.168.0.115
  name: HD2-temperature
  unit_of_measurement: '°C'
  community: monitor
  baseoid: 1.3.6.1.4.1.6574.2.1.1.6.1

- platform: snmp
  host: 192.168.0.115
  name: HDunit
  unit_of_measurement: 'B'
  community: monitor
  baseoid: 1.3.6.1.2.1.25.2.3.1.4.42

- platform: snmp
  host: 192.168.0.115
  name: HDtotal
  unit_of_measurement: 'B'
  community: monitor
  baseoid: 1.3.6.1.2.1.25.2.3.1.5.42

- platform: snmp
  host: 192.168.0.115
  name: HDused
  unit_of_measurement: 'B'
  community: monitor
  baseoid: 1.3.6.1.2.1.25.2.3.1.6.42

- platform: template
  sensors:
    space_left:
      value_template: '{{ ((states("sensor.hdtotal")|int|abs - states("sensor.hdused")|int|abs) * states("sensor.hdunit")|int|abs / 1024 /1024 / 1024) | round(1)}}'
      friendly_name: 'Utrymme kvar NAS'
      unit_of_measurement: 'Gb'

- platform: template 
  sensors:
    coffee_brewing:
      value_template: "{{ states.sensor.fibaro_system_fgwpef_wall_plug_gen5_power.state | float > 1000.0 }}" 
      friendly_name: "Brygger kaffe"

- platform: template
  sensors:
    is_dark:
      value_template: "{{ states.sensor.ljus01.state | int < 10 }}"
      friendly_name: 'Det är mörkt'

- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
    - fog
    - cloudiness
    - lowClouds
    - mediumClouds
    - highClouds
    - dewpointTemperature

- platform: command_line
  name: CPU-temperatur Pi
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'

- platform: command_line
  name: Database
  command: "stat --printf='%s' /home/homeassistant/.homeassistant/home-assistant_v2.db"
  scan_interval: 60
  unit_of_measurement: "Mb"
  value_template: >-
    {% set bytes = value | int %}
    {% set Mbytes = (bytes / 1024 / 1024) | int %}
    {{ Mbytes }}

- platform: command_line
  name: "HASS uptime"
  command: echo "$(($(date +%s) - $(date --date="`systemctl show home-assistant.service -p ActiveEnterTimestamp | awk -F'=' '{print $2}'`" "+%s")))"
  scan_interval: 60
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}

    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 day
      {%- else -%}
        {{ days }} days
      {%- endif -%}
    {%- endif -%}
    {%- if hours > 0 -%}
      {%- if days > 0 -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if hours == 1 -%}
        1 hour
      {%- else -%}
        {{ hours }} hours
      {%- endif -%}
    {%- endif -%}
    {%- if minutes > 0 -%}
      {%- if days > 0 or hours > 0 -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if minutes == 1 -%}
        1 minute
      {%- else -%}
        {{ minutes }} minutes
      {%- endif -%}
    {%- endif -%}
    {%- if seconds > 0 -%}
      {%- if days > 0 or hours > 0 or minutes > 0 -%}
        {{ ', ' }}
      {%- endif -%}
      {%- if seconds == 1 -%}
        1 second
      {%- else -%}
        {{ seconds }} seconds
      {%- endif -%}
    {%- endif -%}

- platform: synologydsm
  host: 192.168.0.115
  username: !secret synology_user
  password: !secret synology_pass
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - volume_size_total
    - volume_size_used
    - volume_percentage_used

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: memory_free
    - type: processor_use
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: since_last_boot


################## Taklampa sovrum
- platform: template
  sensors:
    bedroom_time:
      friendly_name: 'Klockslag'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_slider.bedroom_hour") | int, states("input_slider.bedroom_minutes") | int) }}'
    bedroom_transition:
      friendly_name: 'Transition'
      value_template: '{{ states.input_slider.bedroom_transition.state | int  }} minuter'

################## Kaffebryggare
- platform: template
  sensors:
    coffee_time:
      friendly_name: 'Klockslag'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_slider.coffee_hour") | int, states("input_slider.coffee_minutes") | int) }}'

################## Multisensor SN1
- platform: mqtt
  state_topic: "bruh/sensornode1"
  name: "Ljus01"
  unit_of_measurement: '%'
  value_template: '{{ value_json.ldr }}'

#- platform: mqtt  
#  state_topic: "bruh/sensornode1"  
#  name: "SN1 Temperature"  
#  unit_of_measurement: "°C"  
#  value_template: '{{ value_json.temperature | round(1) }}'  

#- platform: mqtt
#  state_topic: "bruh/sensornode1"
#  name: "SN1 Humidity"
#  unit_of_measurement: "%"
#  value_template: '{{ value_json.humidity | round(1) }}'

#- platform: mqtt
#  state_topic: "bruh/sensornode1"  
#  name: "SN1 PIR"
#  value_template: '{{ value_json.motion }}'

################## ESP_Easy1
- platform: mqtt
  state_topic: "ESP_Easy1/PIR/motion"
  name: "SN2 PIR"

- platform: mqtt
  state_topic: "ESP_Easy1/DHT22/Temperature"
  name: "Temperatur källare"
  unit_of_measurement: "°C"
  value_template: '{{ value | round(1) }}'

- platform: mqtt
  state_topic: "ESP_Easy1/DHT22/Humidity"
  name: "Luftfuktighet källare"
  unit_of_measurement: "rh"
  value_template: '{{ value | round(1) }}'

- platform: mqtt
  state_topic: "zanzito/ke/battery_level"
  name: "Note 8 Batteri"
  unit_of_measurement: "%"

################## ESP_Easy2
- platform: mqtt
  state_topic: "ESP_Easy2/PIR/motion"
  name: "PIR_hall"

################## Kalender
- platform: template
  sensors:
    ke_start_time:
      value_template: '{{ states.calendar.kurteinarssongmailcom.attributes.start_time }}'
      friendly_name: 'Start'
    ke_end_time:
      value_template: '{{ states.calendar.kurteinarssongmailcom.attributes.end_time }}'
      friendly_name: 'Slut'
    ke_message:
      value_template: '{{ states.calendar.kurteinarssongmailcom.attributes.message }}'
      friendly_name: 'Meddelande'
    ke_description:
      value_template: '{{ states.calendar.kurteinarssongmailcom.attributes.description }}'
      friendly_name: 'Beskrivning'
    ke_location:
      value_template: '{{ states.calendar.kurteinarssongmailcom.attributes.location }}'
      friendly_name: 'Plats'

################## Sun
- platform: template
  sensors:
    winlights:
      friendly_name: 'Tänder fönsterlampor'
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) - 2100) | timestamp_custom("%H:%M:%S") }}'
    sun_set:
      friendly_name: 'Solen går ner'
      value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M:%S") }}'
    sun_set_time_left:
      friendly_name: 'Tid innan solen går ner'
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()) - 3600) | timestamp_custom("%H:%M:%S") }}'
    winlights_time_left:
      friendly_name: 'Tid innan fönsterlampor tänds'
      value_template: '{{ (as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(now()) - 2100 - 3600) | timestamp_custom("%H:%M:%S") }}'
    time_now:
      friendly_name: 'Klockslag'
      value_template: '{{ as_timestamp(now()) | timestamp_custom("%H:%M") }}'

################## LED-strip
- platform: template
  sensors:
    slider_rgb_led_strip:
      friendly_name: 'RGB LED-strip'
      value_template: >- 
        {% set r = states.input_slider.led_strip_r.state | int %}
        {% set g = states.input_slider.led_strip_g.state | int %}
        {% set b = states.input_slider.led_strip_b.state | int %}
        ({{ r | int }}, {{ g | int }}, {{ b | int }})
    rgb_led_strip_pv:
      friendly_name: 'RGB'
      value_template: '{{ states.light.led_strip.attributes.rgb_color }}'