title: Viggestorp
views:
# KÖK
  - title: Kök
    panel: false
    id: kitchen
    # The cards to show on this view.
    cards:
      - type: entities
        show_header_toggle: true
        title: Belysning
        entities:
          - switch.win_kitchen1
          - switch.win_kitchen2
          
      - type: entities
        show_header_toggle: false
        title: Kaffebryggare
        entities:
          - switch.fibaro_system_fgwpef_wall_plug_gen5_switch
          - automation.stang_av_kaffebryggaren_efter_30_minuter
          - automation.starta_kaffebryggaren
          - sensor.coffee_time 
          - sensor.coffee_brewing
          - sensor.fibaro_system_fgwpef_wall_plug_gen5_power
          - sensor.fibaro_system_fgwpef_wall_plug_gen5_energy
          
      - type: entities
        show_header_toggle: false
        title: Temperaturer
        entities:
          - sensor.temperature_158d000223f3bc
          - sensor.temperature_9
          - sensor.temperature_7
          
      - type: entities
        show_header_toggle: false
        title: Media
        entities:
          - media_player.kok

      - type: entities
        show_header_toggle: false
        title: Diverse
        entities:
          - binary_sensor.water_leak_sensor_158d0001bc1fab
          - switch.strykjarn

# HALL
  - title: Hall
    id: hall
    # The cards to show on this view.
    cards:
      - type: entities
        title: Belysning
        show_header_toggle: true
        entities:
          - light.fibaro_system_fgd212_dimmer_2_level_3       
          - light.fibaro_system_fgd212_dimmer_2_level_5
          
      - type: entities
        title: Förbrukning
        show_header_toggle: false
        entities:
          - sensor.fibaro_system_fgd212_dimmer_2_power_3
          - sensor.fibaro_system_fgd212_dimmer_2_energy_2        
          - sensor.fibaro_system_fgd212_dimmer_2_power_5
          - sensor.fibaro_system_fgd212_dimmer_2_energy_3
          
      - type: entities
        title: Temperatur
        show_header_toggle: false
        entities:
          - sensor.temperatur_hall
          
      - type: entities
        show_header_toggle: false
        title: Diverse
        entities:
          - binary_sensor.presence_4
          - sensor.pir_hall
          
# VARDAGSRUM
  - title: Vardagsrum
    panel: false
    id: livingroom
    # The cards to show on this view.
    cards:
      - type: entities
        show_header_toggle: true
        title: Belysning
        entities:
          - switch.win_livingroom_1
          - switch.win_livingroom_2
          
      - type: entities
        show_header_toggle: false
        title: Väderstation
        entities:
          - sensor.netatmo_vardagsrum_temperature_2
          - sensor.netatmo_vardagsrum_humidity_2
          - sensor.netatmo_vardagsrum_pressure_2
          - sensor.netatmo_vardagsrum_co2_2
          - sensor.netatmo_vardagsrum_noise_2
          
      - type: entities
        show_header_toggle: false
        title: Media
        entities:
          - media_player.tv_vardagsrum
          
      - type: entities
        show_header_toggle: false
        title: Diverse
        entities:
          - binary_sensor.openclose_11
          
# SOVRUM
  - title: Sovrum
    id: sleeping
    # The cards to show on this view.
    cards:
      - type: entities
        title: Belysning
        show_header_toggle: false
        entities:
          - switch.win_bedroom
          - light.fibaro_system_fgd212_dimmer_2_level
          - switch.sanglampa
          
      - type: entities
        title: Förbrukning
        show_header_toggle: false
        entities:
          - sensor.fibaro_system_fgd212_dimmer_2_power
          - sensor.fibaro_system_fgd212_dimmer_2_energy
          
      - type: entities
        title: Temperatur
        show_header_toggle: false
        entities:
          - sensor.temperatur_sovrum_2
          
# FÖNSTERLAMPOR
  - title: Fönsterlampor
    panel: false
    id: winlight
    # The cards to show on this view.
    cards:
      - type: entities
        title: Fönsterlampor
        show_header_toggle: true
        entities:
          - switch.win_livingroom_1
          - switch.win_livingroom_2
          - switch.win_kitchen1
          - switch.win_kitchen2
          - switch.win_bedroom
          - sensor.sun_set
          - sensor.winlight_on
          - sensor.smhi_mean_value_of_total_cloud_cover

          
      - type: entity-filter
        show_header_toggle: true
        entities:
          - switch.win_livingroom_1
          - switch.win_livingroom_2
          - switch.win_kitchen1
          - switch.win_kitchen2
          - switch.win_bedroom
        state_filter:
          - "on"
        card:
          type: entities
          title: Tända fönsterlampor
          
      - type: history-graph
        title: Ljus
        show_header_toggle: false
        refresh_interval: 60
        hours_to_show: 24
        entities:
          - sensor.filtrerat_ljus_ute
          - sensor.ljus01
          

# TEMPERATURER          
  - title: Temperaturer
    id: temperatures
    # The cards to show on this view.
    cards:
      - type: entities
        title: Temperaturer
        show_header_toggle: false
        entities:
          - sensor.temperature_158d000223f3bc
          - sensor.netatmo_ute_soder_temperature_2
          
      - type: history-graph
        title: Utetemperaturer
        show_header_toggle: false
        refresh_interval: 1800
        hours_to_show: 24
        entities:
          - sensor.temperature_158d000223f3bc
          - sensor.netatmo_ute_soder_temperature_2

# TRACKER
  - title: Tracker
    id: tracker
    # The cards to show on this view.
    cards:
      - type: glance
        title: Mobiler
        entities:
          - device_tracker.ke
          - device_tracker.70700dd0ac07
          
      - type: map
        title: Karta
        aspect_ratio: 100%
        entities:
          - zone.home
          - device_tracker.ke
          - device_tracker.70700dd0ac07

# AUTOMATION
  - title: Automation
    panel: false
    # Optional unique id for direct access /lovelace/${id}
    id: auto
    #theme: dark-mode
    # The cards to show on this view.
    cards:
      - type: entities
        title: Automation
        show_header_toggle: false
        entities:
          - automation.balkongdorr_oppnas
          - automation.balkongdorr_stangs
          - automation.brandlarm
          - automation.diskmaskin_oversvammning
          - automation.dorrklocka
          - automation.dorrklocka_single_click
          - automation.fonsterlampor_av_single_click
          - automation.fonsterlampor_pa_double_click
          - automation.godnatt_long_click_press
          - automation.kaffet_ar_fardigt
          - automation.ledstrip
          - automation.ledstripljus
          - automation.slack_fonsterlampor
          - automation.slack_fonsterlampor_nar_tvn_stangs_av
          - automation.slack_hallampa_efter_rorelse
          - automation.slack_lampa_efter_rorelse
          - automation.sovrum_taklampa_automatik
          - automation.stang_av_kaffebryggaren_efter_30_minuter
          - automation.stang_av_strykjarnet_efter_45_minuter
          - automation.stang_av_uttag_vid_sangen
          - automation.starta_kaffebryggaren
          - automation.tand_fonsterlampor_med_ljussensor
          - automation.tand_hallampa_1
          - automation.tand_hallampa_vid_rorelse
          - automation.tand_lampa_vid_rorelse
        #state_filter:
        #  - "on"
        #card:
        #  type: entities
        #  title: Aktiva
          
      - type: entity-filter
        show_header_toggle: false
        entities:
          - automation.balkongdorr_oppnas
          - automation.balkongdorr_stangs
          - automation.brandlarm
          - automation.diskmaskin_oversvammning
          - automation.dorrklocka
          - automation.dorrklocka_single_click
          - automation.fonsterlampor_av_single_click
          - automation.fonsterlampor_pa_double_click
          - automation.godnatt_long_click_press
          - automation.kaffet_ar_fardigt
          - automation.ledstrip
          - automation.ledstripljus
          - automation.slack_fonsterlampor
          - automation.slack_fonsterlampor_nar_tvn_stangs_av
          - automation.slack_hallampa_efter_rorelse
          - automation.slack_lampa_efter_rorelse
          - automation.sovrum_taklampa_automatik
          - automation.stang_av_kaffebryggaren_efter_30_minuter
          - automation.stang_av_strykjarnet_efter_45_minuter
          - automation.stang_av_uttag_vid_sangen
          - automation.starta_kaffebryggaren
          - automation.tand_fonsterlampor_med_ljussensor
          - automation.tand_hallampa_1
          - automation.tand_hallampa_vid_rorelse
          - automation.tand_lampa_vid_rorelse
        state_filter:
          - "off"
        card:
          type: entities
          title: Avstängda
          
# BATTERIER
  - title: Batterier
    id: batterier
    # The cards to show on this view.
    cards:
      - type: entities
        title: Batterier
        show_header_toggle: false
        entities:
          - sensor.batt_door_balcony   
          - sensor.batt_leak_dishwasher
          - sensor.batt_switch_window
          - sensor.batt_temp_north
          - sensor.batt_temp_refrig
          - sensor.batt_temp_sleep
          - sensor.batt_temp_freezer